language: ruby
rvm:
    - 2.1.0
    - ruby-head
bundler_args: -j4 --without development
before_install:
    - export NOKOGIRI_USE_SYSTEM_LIBRARIES=1
before_script:
    - cp config/database.yml.example config/database.yml
    - cp config/secrets.yml.example config/secrets.yml
    - bundle exec rake db:migrate RAILS_ENV=test
matrix:
    allow_failures:
        - ruby-head
